version: '3.8'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: fixer-upper
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
